# Generated by Django 4.1.6 on 2023-02-14 12:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('sup_desc', models.TextField(max_length=2000)),
                ('check_double_text_1', models.TextField(max_length=200)),
                ('check_double_text_2', models.TextField(max_length=200)),
                ('check_double_text_3', models.TextField(max_length=200)),
                ('inf_desc', models.TextField(max_length=2000)),
                ('is_visible', models.BooleanField(default=True)),
                ('photo', models.ImageField(upload_to='about/%y_%m_%d')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50, unique=True)),
                ('position', models.SmallIntegerField(unique=True)),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='Chefs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50, unique=True)),
                ('com_desc', models.TextField(max_length=200)),
                ('position', models.SmallIntegerField()),
                ('is_visible', models.BooleanField(default=True)),
                ('name', models.TextField(max_length=100)),
                ('desc', models.TextField(max_length=200)),
                ('photo', models.ImageField(upload_to='collective')),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.TextField(max_length=20)),
                ('phone_add', models.TextField(blank=True, max_length=20)),
                ('address', models.TextField(max_length=200)),
                ('email', models.TextField(max_length=50)),
                ('email_add', models.TextField(max_length=50)),
                ('socials', models.TextField(blank=True, max_length=100)),
                ('add_information', models.TextField(blank=True, max_length=500)),
                ('sub_title', models.TextField(blank=True, max_length=500)),
                ('open_days_1', models.TextField(max_length=150)),
                ('open_hours_1', models.TextField(max_length=50)),
                ('open_days_2', models.TextField(blank=True, max_length=150)),
                ('open_hours_2', models.TextField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('position', models.SmallIntegerField()),
                ('sup_desc', models.TextField(blank=True, max_length=500)),
                ('point_text_1', models.TextField(max_length=200)),
                ('point_text_2', models.TextField(max_length=200)),
                ('point_text_3', models.TextField(max_length=200)),
                ('inf_desc', models.TextField(blank=True, max_length=500)),
                ('is_visible', models.BooleanField(default=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('photo', models.ImageField(blank=True, upload_to='events')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='gallery')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Error in phone number', regex='^\\+?3?8?0\\d{2}[- ]?(\\d[- ]?){7}$')])),
                ('persons', models.SmallIntegerField()),
                ('message', models.TextField(blank=True, max_length=250)),
                ('date', models.DateField(auto_now_add=True)),
                ('date_processing', models.DateField(auto_now=True)),
                ('is_processed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.TextField(max_length=70)),
                ('author_desc', models.TextField(max_length=500)),
                ('quote', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='WhyUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50, unique=True)),
                ('subtitle', models.CharField(db_index=True, max_length=200, unique=True)),
                ('desc_1', models.TextField(max_length=200)),
                ('desc_2', models.TextField(max_length=200)),
                ('desc_3', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50, unique=True)),
                ('position', models.SmallIntegerField()),
                ('is_visible', models.BooleanField(default=True)),
                ('ingredients', models.CharField(max_length=255)),
                ('desc', models.TextField(blank=True, max_length=500)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('photo', models.ImageField(blank=True, upload_to='dishes')),
                ('is_special', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='main_page.category')),
            ],
            options={
                'ordering': ('category', 'position'),
            },
        ),
    ]
