# Generated by Django 4.1.6 on 2023-02-16 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonials',
            name='photo',
            field=models.ImageField(default=1, upload_to='testimonials'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chefs',
            name='com_desc',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='chefs',
            name='title',
            field=models.CharField(blank=True, db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='photo',
            field=models.ImageField(upload_to='events'),
        ),
    ]
